/**
 * Copyright 2000-present Liferay, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.liferay.blade.samples.servicebuilder.adq.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Bar service. Represents a row in the &quot;ADQ_Bar&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.blade.samples.servicebuilder.adq.model.impl.BarModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.blade.samples.servicebuilder.adq.model.impl.BarImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Bar
 * @see com.liferay.blade.samples.servicebuilder.adq.model.impl.BarImpl
 * @see com.liferay.blade.samples.servicebuilder.adq.model.impl.BarModelImpl
 * @generated
 */
@ProviderType
public interface BarModel extends BaseModel<Bar>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bar model instance should use the {@link Bar} interface instead.
	 */

	/**
	 * Returns the primary key of this bar.
	 *
	 * @return the primary key of this bar
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bar.
	 *
	 * @param primaryKey the primary key of this bar
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this bar.
	 *
	 * @return the uuid of this bar
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this bar.
	 *
	 * @param uuid the uuid of this bar
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the bar ID of this bar.
	 *
	 * @return the bar ID of this bar
	 */
	public long getBarId();

	/**
	 * Sets the bar ID of this bar.
	 *
	 * @param barId the bar ID of this bar
	 */
	public void setBarId(long barId);

	/**
	 * Returns the group ID of this bar.
	 *
	 * @return the group ID of this bar
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this bar.
	 *
	 * @param groupId the group ID of this bar
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this bar.
	 *
	 * @return the company ID of this bar
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this bar.
	 *
	 * @param companyId the company ID of this bar
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this bar.
	 *
	 * @return the user ID of this bar
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this bar.
	 *
	 * @param userId the user ID of this bar
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this bar.
	 *
	 * @return the user uuid of this bar
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this bar.
	 *
	 * @param userUuid the user uuid of this bar
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this bar.
	 *
	 * @return the user name of this bar
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this bar.
	 *
	 * @param userName the user name of this bar
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this bar.
	 *
	 * @return the create date of this bar
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this bar.
	 *
	 * @param createDate the create date of this bar
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this bar.
	 *
	 * @return the modified date of this bar
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this bar.
	 *
	 * @param modifiedDate the modified date of this bar
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the field1 of this bar.
	 *
	 * @return the field1 of this bar
	 */
	@AutoEscape
	public String getField1();

	/**
	 * Sets the field1 of this bar.
	 *
	 * @param field1 the field1 of this bar
	 */
	public void setField1(String field1);

	/**
	 * Returns the field2 of this bar.
	 *
	 * @return the field2 of this bar
	 */
	public boolean getField2();

	/**
	 * Returns <code>true</code> if this bar is field2.
	 *
	 * @return <code>true</code> if this bar is field2; <code>false</code> otherwise
	 */
	public boolean isField2();

	/**
	 * Sets whether this bar is field2.
	 *
	 * @param field2 the field2 of this bar
	 */
	public void setField2(boolean field2);

	/**
	 * Returns the field3 of this bar.
	 *
	 * @return the field3 of this bar
	 */
	public int getField3();

	/**
	 * Sets the field3 of this bar.
	 *
	 * @param field3 the field3 of this bar
	 */
	public void setField3(int field3);

	/**
	 * Returns the field4 of this bar.
	 *
	 * @return the field4 of this bar
	 */
	public Date getField4();

	/**
	 * Sets the field4 of this bar.
	 *
	 * @param field4 the field4 of this bar
	 */
	public void setField4(Date field4);

	/**
	 * Returns the field5 of this bar.
	 *
	 * @return the field5 of this bar
	 */
	@AutoEscape
	public String getField5();

	/**
	 * Sets the field5 of this bar.
	 *
	 * @param field5 the field5 of this bar
	 */
	public void setField5(String field5);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Bar bar);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Bar> toCacheModel();

	@Override
	public Bar toEscapedModel();

	@Override
	public Bar toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}