/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.blade.workflow.basic.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Baz service. Represents a row in the &quot;Workflow_Baz&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.blade.workflow.basic.model.impl.BazModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.blade.workflow.basic.model.impl.BazImpl</code>.
 * </p>
 *
 * @author Inácio Nery
 * @see Baz
 * @generated
 */
@ProviderType
public interface BazModel
	extends BaseModel<Baz>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a baz model instance should use the {@link Baz} interface instead.
	 */

	/**
	 * Returns the primary key of this baz.
	 *
	 * @return the primary key of this baz
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this baz.
	 *
	 * @param primaryKey the primary key of this baz
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this baz.
	 *
	 * @return the uuid of this baz
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this baz.
	 *
	 * @param uuid the uuid of this baz
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the baz ID of this baz.
	 *
	 * @return the baz ID of this baz
	 */
	public long getBazId();

	/**
	 * Sets the baz ID of this baz.
	 *
	 * @param bazId the baz ID of this baz
	 */
	public void setBazId(long bazId);

	/**
	 * Returns the group ID of this baz.
	 *
	 * @return the group ID of this baz
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this baz.
	 *
	 * @param groupId the group ID of this baz
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this baz.
	 *
	 * @return the company ID of this baz
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this baz.
	 *
	 * @param companyId the company ID of this baz
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this baz.
	 *
	 * @return the user ID of this baz
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this baz.
	 *
	 * @param userId the user ID of this baz
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this baz.
	 *
	 * @return the user uuid of this baz
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this baz.
	 *
	 * @param userUuid the user uuid of this baz
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this baz.
	 *
	 * @return the user name of this baz
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this baz.
	 *
	 * @param userName the user name of this baz
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this baz.
	 *
	 * @return the create date of this baz
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this baz.
	 *
	 * @param createDate the create date of this baz
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this baz.
	 *
	 * @return the modified date of this baz
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this baz.
	 *
	 * @param modifiedDate the modified date of this baz
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}