/**
 * Copyright 2000-present Liferay, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.liferay.blade.workflow.asset.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Qux service. Represents a row in the &quot;Workflow_Qux&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.blade.workflow.asset.model.impl.QuxModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.blade.workflow.asset.model.impl.QuxImpl</code>.
 * </p>
 *
 * @author Inácio Nery
 * @see Qux
 * @generated
 */
@ProviderType
public interface QuxModel
	extends BaseModel<Qux>, GroupedModel, ShardedModel, StagedAuditedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qux model instance should use the {@link Qux} interface instead.
	 */

	/**
	 * Returns the primary key of this qux.
	 *
	 * @return the primary key of this qux
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this qux.
	 *
	 * @param primaryKey the primary key of this qux
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this qux.
	 *
	 * @return the uuid of this qux
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this qux.
	 *
	 * @param uuid the uuid of this qux
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the qux ID of this qux.
	 *
	 * @return the qux ID of this qux
	 */
	public long getQuxId();

	/**
	 * Sets the qux ID of this qux.
	 *
	 * @param quxId the qux ID of this qux
	 */
	public void setQuxId(long quxId);

	/**
	 * Returns the group ID of this qux.
	 *
	 * @return the group ID of this qux
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this qux.
	 *
	 * @param groupId the group ID of this qux
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this qux.
	 *
	 * @return the company ID of this qux
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this qux.
	 *
	 * @param companyId the company ID of this qux
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this qux.
	 *
	 * @return the user ID of this qux
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this qux.
	 *
	 * @param userId the user ID of this qux
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this qux.
	 *
	 * @return the user uuid of this qux
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this qux.
	 *
	 * @param userUuid the user uuid of this qux
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this qux.
	 *
	 * @return the user name of this qux
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this qux.
	 *
	 * @param userName the user name of this qux
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this qux.
	 *
	 * @return the create date of this qux
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this qux.
	 *
	 * @param createDate the create date of this qux
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this qux.
	 *
	 * @return the modified date of this qux
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this qux.
	 *
	 * @param modifiedDate the modified date of this qux
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this qux.
	 *
	 * @return the status of this qux
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this qux.
	 *
	 * @param status the status of this qux
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this qux.
	 *
	 * @return the status by user ID of this qux
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this qux.
	 *
	 * @param statusByUserId the status by user ID of this qux
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this qux.
	 *
	 * @return the status by user uuid of this qux
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this qux.
	 *
	 * @param statusByUserUuid the status by user uuid of this qux
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this qux.
	 *
	 * @return the status by user name of this qux
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this qux.
	 *
	 * @param statusByUserName the status by user name of this qux
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this qux.
	 *
	 * @return the status date of this qux
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this qux.
	 *
	 * @param statusDate the status date of this qux
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this qux is approved.
	 *
	 * @return <code>true</code> if this qux is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this qux is denied.
	 *
	 * @return <code>true</code> if this qux is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this qux is a draft.
	 *
	 * @return <code>true</code> if this qux is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this qux is expired.
	 *
	 * @return <code>true</code> if this qux is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this qux is inactive.
	 *
	 * @return <code>true</code> if this qux is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this qux is incomplete.
	 *
	 * @return <code>true</code> if this qux is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this qux is pending.
	 *
	 * @return <code>true</code> if this qux is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this qux is scheduled.
	 *
	 * @return <code>true</code> if this qux is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}