name: SF and Build Test
on:
  pull_request:
    branches: [ master, 7.3, 7.2 ]
jobs:
  CheckSourceFormatting:
    name: Check source formatting
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        shell: bash
        run: |
          cd liferay-workspace
          ./gradlew --no-daemon checkSourceFormatting
          cd ../maven
          mvn source-formatter:format
  Maven-Linux-JDK8:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        cd maven
        mvn clean package
  Maven-Linux-JDK11:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: |
        cd maven
        mvn clean package
  Maven-MacOS-JDK8:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        cd maven
        mvn clean package
  Maven-Windows-JDK8:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        cd maven
        mvn clean package
  Gradle-Linux-JDK8:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        cd liferay-workspace
        ./gradlew --no-daemon clean assemble
  Gradle-Linux-JDK11:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: |
        cd liferay-workspace
        ./gradlew --no-daemon clean assemble
  Gradle-MacOS-JDK8:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        cd liferay-workspace
        ./gradlew --no-daemon clean assemble
  Gradle-Windows-JDK8:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        cd liferay-workspace
        ./gradlew --no-daemon clean assemble

  Integration-Test-JDK11:
    name: Workspace Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
          cache: gradle

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Integration Test
        shell: bash
        run: |
          ./gradlew --no-daemon buildService build testIntegration        
        
  Yarn-Linux-JDK8:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Yarn
      run: |
        cd yarn-workspace
        ./gradlew --no-daemon clean build
  Yarn-Linux-JDK11:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Yarn
      run: |
        cd yarn-workspace
        ./gradlew --no-daemon clean build
  Yarn-MacOS-JDK8:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Yarn
      run: |
        cd yarn-workspace
        ./gradlew --no-daemon clean build
  Yarn-Windows-JDK8:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Yarn
      run: |
        cd yarn-workspace
        ./gradlew --no-daemon clean build

  Integration-Test-JDK11:
    name: Workspace Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
          cache: gradle

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Integration Test
        shell: bash
        working-directory: ./liferay-workspace-test-integration-sample
        run: |
          ./gradlew --no-daemon buildService build testIntegration        
                